// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYkTopZv_8tOB34kt3yCun_MRqtHJdbg',
    appId: '1:90150756614:web:4e4dbbc57d642065fd7e87',
    messagingSenderId: '90150756614',
    projectId: 'newcoffeeshopapp',
    authDomain: 'newcoffeeshopapp.firebaseapp.com',
    storageBucket: 'newcoffeeshopapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDw0U1v8xfpD9VacJ_JYqkbhmnnFteFQI',
    appId: '1:90150756614:android:2f4f161ec9eb9c5afd7e87',
    messagingSenderId: '90150756614',
    projectId: 'newcoffeeshopapp',
    storageBucket: 'newcoffeeshopapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhm1-yNEuFoHm-ddcPUQDeD1GMTOLPRNQ',
    appId: '1:90150756614:ios:462f2e9c2e015b0dfd7e87',
    messagingSenderId: '90150756614',
    projectId: 'newcoffeeshopapp',
    storageBucket: 'newcoffeeshopapp.firebasestorage.app',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhm1-yNEuFoHm-ddcPUQDeD1GMTOLPRNQ',
    appId: '1:90150756614:ios:462f2e9c2e015b0dfd7e87',
    messagingSenderId: '90150756614',
    projectId: 'newcoffeeshopapp',
    storageBucket: 'newcoffeeshopapp.firebasestorage.app',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKYkTopZv_8tOB34kt3yCun_MRqtHJdbg',
    appId: '1:90150756614:web:6e9c85933bab85effd7e87',
    messagingSenderId: '90150756614',
    projectId: 'newcoffeeshopapp',
    authDomain: 'newcoffeeshopapp.firebaseapp.com',
    storageBucket: 'newcoffeeshopapp.firebasestorage.app',
  );
}
